/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Miry
 * Created: 2/12/2016
 */

CREATE TABLE CONDUCTOR(ID_CONDUCTOR INTEGER,NOMBRE VARCHAR2(30),DIR VARCHAR2(50),
TEL VARCHAR2(15), EXPERIENCIA INTEGER, SALUD VARCHAR2(20), CONSTRAINT PK_ID_CONDUCTOR
PRIMARY KEY(ID_CONDUCTOR));


CREATE PROCEDURE GUARDAR_CONDUCTOR(
MY_ID_CONDUCTOR  NUMBER,
MY_NOMBRE  VARCHAR2,
MY_DIR  VARCHAR2,
MY_TEL  VARCHAR2,
MY_EXPERIENCIA  NUMBER,
MY_SALUD  VARCHAR2
)IS
BEGIN
INSERT INTO CONDUCTOR(ID_CONDUCTOR,NOMBRE,DIR,TEL,EXPERIENCIA,SALUD)
 VALUES(MY_ID_CONDUCTOR,MY_NOMBRE,MY_DIR,MY_TEL,MY_EXPERIENCIA,MY_SALUD);
END ;

INTO hr.cliente(id,nombres,apellidos,fecha_afiliacion)




